import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  technical: [
    'technical/index',
    {
      label: 'Programming Language Pragmatics',
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Programming Language Pragmatics',
        description:
          "Programming Language Pragmatics笔记",
      },
      items: [
        {type: 'autogenerated', dirName: 'technical/programming-language-pragmatics'},
      ],
    }
  ],
  life: [{type: 'autogenerated', dirName: 'life'}],
  tools: [{type: 'autogenerated', dirName: 'tools'}],
};

export default sidebars;
