import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  technical: [
    'technical/introduction',
    {
      label: 'Programming Language Pragmatics',
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Programming Language Pragmatics',
        description:
          "Programming Language Pragmatics笔记",
      },
      items:[
          'technical/programming-language-pragmatics/01',
          'technical/programming-language-pragmatics/02',
          'technical/programming-language-pragmatics/03',
          'technical/programming-language-pragmatics/04',
          'technical/programming-language-pragmatics/05',
          'technical/programming-language-pragmatics/06',
          'technical/programming-language-pragmatics/07',
          'technical/programming-language-pragmatics/08',
      ],
    }
  ],
  life: [{type: 'autogenerated', dirName: 'life'}],
  tools: [{type: 'autogenerated', dirName: 'tools'}],
};

export default sidebars;
